var myString = `public class Puzzle{
  public static void main(String arg[]){
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{0}");
    System.out.print("-");
    System.out.print("{1}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{2}");
    System.out.print("-");
    System.out.print("{3}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{4}");
    System.out.print("-");
    System.out.print("{5}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{6}");
    System.out.print("-");
    System.out.print("{7}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{8}");
    System.out.print("-");
    System.out.print("{9}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{10}");
    System.out.print("-");
    System.out.print("{11}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{12}");
    System.out.print("-");
    System.out.print("{13}");
    System.out.println();
    System.out.println();
    System.out.print(")");
    System.out.print("_");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("\\\\");
    System.out.print("_");
    System.out.print("V");
    System.out.print("_");
    System.out.print("/");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(")");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("0");
    System.out.print("x");
    System.out.print("0");
    System.out.print("_");
    System.out.print("_");
    System.out.print("_");
    System.out.print("(");
    System.out.println();
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print(" ");
    System.out.print("{14}");
    System.out.print("-");
    System.out.print("{15}");
    System.out.println();
  }
}`

module.exports = myString;
